const menu = document.querySelector('#mobile_menu');
const menuLinks = document.querySelector('.navbar_menu');
menu.addEventListener('click', function () {
  menu.classList.toggle('is-active');
  menuLinks.classList.toggle('active');
});
const quotes = {
happy: [
  "Happiness looks gorgeous on you.",
  "Choose joy every day.",
  "Smile — it's free therapy.",
  "Happiness is homemade.",
  "Stay close to what makes you feel alive.",
  "Joy is the best makeup.",
  "Be a voice of happiness.",
  "Smiles are contagious.",
  "Find joy in the ordinary.",
  "Be the sunshine.",
  "Dream big, smile often.",
  "Good vibes only.",
  "Life is better when you’re laughing.",
  "Happiness begins with gratitude.",
  "Joy is a choice.",
  "Laugh more, worry less.",
  "Collect moments, not things.",
  "Be happy with what you have.",
  "Let go and let happiness come.",
  "Breathe. Smile. Repeat.",
  "Spark joy wherever you go.",
  "Happiness never goes out of style.",
  "Gratitude turns what we have into enough.",
  "Small steps, big smiles.",
  "You deserve good things.",
  "Be kind. Be happy.",
  "Find beauty in every day.",
  "Make today count.",
  "You are enough.",
  "Celebrate the little things.",
  "Happiness blooms from within.",
  "Joy is the best gift.",
  "Bloom with grace.",
  "Smile at strangers.",
  "Live simply, love deeply.",
  "Choose happiness today.",
  "Be gentle with yourself.",
  "Happiness is a warm cup and a good book.",
  "Sunshine on your mind.",
  "Keep your heart light.",
  "Let your smile change the world.",
  "Savor the small wins.",
  "Happiness is a quiet morning.",
  "Dance like no one’s watching.",
  "Happiness is a choice, not a destination.",
  "Fill your day with laughter.",
  "Happiness is an inside job.",
  "Chase joy, not perfection.",
  "Let your heart be light.",
  "Happiness grows from gratitude.",
  "Smile — it's your best accessory.",
  "Happiness is found in little moments.",
  "Wake up with a grateful heart.",
  "Be the reason someone smiles today.",
  "Happiness is sharing a laugh.",
  "Live for the moments you can’t put into words.",
  "Happiness is a well-made cup of tea.",
  "Find joy in the journey.",
  "Happiness is a cozy blanket and a good friend.",
  "Laugh until your cheeks hurt.",
  "Kindness multiplies happiness.",
  "Happiness is a mind at peace.",
  "Carry sunshine in your pocket.",
  "Happiness is catching butterflies of thought.",
  "Smile: it's an instant mood-lift.",
  "Happiness is a little bit of magic each day.",
  "Be curious, be happy.",
  "Happiness is giving and receiving hugs.",
  "Enjoy the simple pleasures.",
  "Happiness is a fresh start.",
  "Let joy be your compass.",
  "Happiness is the sound of laughter.",
  "Keep your face to the sun.",
  "Happiness is a shared joke.",
  "Embrace the small delights.",
  "Happiness is singing in the rain.",
  "Choose wonder, choose joy.",
  "Happiness is a playful heart.",
  "Radiate positivity.",
  "Happiness is a slow walk on a bright day.",
  "Find reasons to smile.",
  "Happiness is being with people you love.",
  "Live with a grateful heart.",
  "Happiness is a creative moment.",
  "Take a deep breath and smile.",
  "Happiness is a kind word.",
  "Celebrate your wins, however small.",
  "Happiness is the warmth of a memory.",
  "Keep chasing that bright feeling.",
  "Happiness is noticing tiny miracles.",
  "Share your light freely.",
  "Happiness is the present you give yourself."
],
sad: [
  "Tears are words the heart can’t express.",
  "Every storm eventually runs out of rain.",
  "Sometimes silence is the loudest cry.",
  "It’s okay to not be okay.",
  "Sadness is a sea, and sometimes we drown.",
  "Even the moon has scars.",
  "Crying doesn’t mean you’re weak.",
  "Some memories hurt no matter how old they are.",
  "People leave, but the pain stays.",
  "Smiling outside, breaking inside.",
  "Sometimes the strongest hearts feel the most pain.",
  "I miss the person I used to be.",
  "Not all wounds are visible.",
  "I wish things were different.",
  "I’m tired of being strong.",
  "Sometimes goodbye is the only way.",
  "Healing takes time, and that’s okay.",
  "You never know how broken someone is behind their smile.",
  "I pretend I’m fine, but I’m not.",
  "It hurts to care so much.",
  "I’m tired of fighting battles I can’t win.",
  "Sometimes loneliness is safer than love.",
  "I’m hurting, but I don’t know how to say it.",
  "Not everything broken can be fixed.",
  "I don’t recognize myself anymore.",
  "The saddest goodbyes are those never said.",
  "I hide my sadness so I don’t burden others.",
  "I miss someone I never had.",
  "Loneliness is louder at night.",
  "The world gets quieter when you’re hurting.",
  "I wish I could unfeel everything.",
  "It hurts when people forget you.",
  "My heart is tired.",
  "Sometimes love is not enough.",
  "The saddest part is pretending you’re okay.",
  "I’m slowly losing pieces of myself.",
  "Some nights are heavier than others.",
  "I keep everything inside because no one listens.",
  "I don’t know how to stop hurting.",
  "I feel too much, and it hurts.",
  "The hardest battles are fought in silence.",
  "I’m surrounded, yet I feel alone.",
  "I miss the person I thought you were.",
  "I wish you had stayed.",
  "Some scars never fade.",
  "You broke me without even trying.",
  "Losing you changed everything.",
  "I didn’t know goodbye would hurt forever.",
  "I’m tired of pretending.",
  "Trust dies with betrayal.",
  "You left, but the memories didn’t.",
  "I break silently.",
  "I’m not the same anymore.",
  "I hate that I still care.",
  "Time doesn’t heal everything.",
  "My heart is bruised, not broken.",
  "I’ve forgotten how to feel happy.",
  "The world doesn’t stop for broken hearts.",
  "Sadness is heavy.",
  "I miss us.",
  "I wish someone understood.",
  "I’m tired of being disappointed.",
  "I feel empty inside.",
  "These nights are endless.",
  "I gave too much, you gave too little.",
  "I hate the way good things end.",
  "I’m scared of caring again.",
  "I don’t know who I am without my sadness.",
  "I outgrew people who never wanted to grow with me.",
  "My heart aches quietly.",
  "The hardest goodbye is the silent one.",
  "I should have walked away sooner.",
  "I miss how simple things used to be.",
  "Loving you cost me myself.",
  "I’m tired of missing people.",
  "Some feelings never fade.",
  "I want to forget, but my heart remembers.",
  "I let go, but it still hurts.",
  "Some nights I break for no reason.",
  "I smile so people won’t ask questions.",
  "I’m exhausted from feeling so deeply.",
  "I love deeply, and it destroys me.",
  "I don’t know how to fix myself.",
  "The past haunts me.",
  "I stopped explaining because no one cared.",
  "I carry pain I never talk about.",
  "I wish I didn’t feel so much.",
  "I don’t know what happiness feels like anymore.",
  "Some people disappear without leaving, just by changing.",
  "I’m scared of being forgotten.",
  "I don’t know how much more I can take.",
  "You left me with unanswered questions.",
  "I lost myself trying to keep you.",
  "I miss the days when I felt alive.",
  "I don’t want to be strong anymore.",
  "I’m tired of starting over.",
  "I wish I could escape my own thoughts.",
  "I want peace, not numbness.",
  "I hope one day this pain makes sense.",
  "Even broken hearts keep beating."
],
inspirational: [
  "The best way to predict the future is to create it.",
  "Dream big and dare to fail.",
  "Success is not final, failure is not fatal.",
  "Small steps every day lead to big results.",
  "Believe you can and you're halfway there.",
  "Don’t wait for opportunity, create it.",
  "Your limitation—it’s only your imagination.",
  "Push yourself, because no one else is going to do it for you.",
  "Great things never come from comfort zones.",
  "Dream it. Wish it. Do it.",
  "Do something today that your future self will thank you for.",
  "Little things make big days.",
  "It always seems impossible until it’s done.",
  "Don’t stop when you’re tired. Stop when you’re done.",
  "Sometimes we’re tested not to show our weaknesses, but to discover our strengths.",
  "The harder you work for something, the greater you’ll feel when you achieve it.",
  "Don’t wait for the perfect moment. Take the moment and make it perfect.",
  "Success doesn’t just find you. You have to go out and get it.",
  "Don’t watch the clock; do what it does. Keep going.",
  "The key to success is to focus on goals, not obstacles.",
  "Believe in yourself and all that you are.",
  "Doubt kills more dreams than failure ever will.",
  "The only limit to our realization of tomorrow is our doubts today.",
  "Opportunities don’t happen. You create them.",
  "Do what you can with all you have, wherever you are.",
  "The secret of getting ahead is getting started.",
  "Don’t wait for things to happen. Make them happen.",
  "You don’t have to be great to start, but you have to start to be great.",
  "Hard work beats talent when talent doesn’t work hard.",
  "The way to get started is to quit talking and begin doing.",
  "Success is the sum of small efforts repeated day in and day out.",
  "Motivation is what gets you started. Habit is what keeps you going.",
  "Act as if what you do makes a difference. It does.",
  "Go the extra mile. It’s never crowded.",
  "Don’t limit your challenges. Challenge your limits.",
  "The only way to achieve the impossible is to believe it is possible.",
  "Push yourself because no one else is going to do it for you.",
  "Start where you are. Use what you have. Do what you can.",
  "Do what you love and the money will follow.",
  "Success usually comes to those who are too busy to be looking for it.",
  "The harder the struggle, the more glorious the triumph.",
  "Dream it, believe it, achieve it.",
  "Your only limit is your mind.",
  "Great things take time. Be patient.",
  "Don’t quit. Suffer now and live the rest of your life as a champion.",
  "Work hard in silence, let success make the noise.",
  "The distance between dreams and reality is called action.",
  "It’s not about being the best. It’s about being better than you were yesterday.",
  "You are stronger than you think.",
  "Challenges are what make life interesting.",
  "The only place where success comes before work is in the dictionary.",
  "Do something today that your future self will thank you for.",
  "Your passion is waiting for your courage to catch up.",
  "Focus on your goal. Don’t look in any direction but ahead.",
  "Don’t be afraid to give up the good to go for the great.",
  "Success is walking from failure to failure with no loss of enthusiasm.",
  "Fall seven times and stand up eight.",
  "The best revenge is massive success.",
  "You are never too old to set another goal or to dream a new dream.",
  "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.",
  "Impossible is just an opinion.",
  "The expert in anything was once a beginner.",
  "Keep going. Everything you need will come to you at the perfect time.",
  "Stay positive, work hard, make it happen.",
  "Don’t count the days, make the days count.",
  "Difficulties in life don’t come to destroy you. They come to help you realize your potential.",
  "Success is the sum of small efforts, repeated day in and day out.",
  "If it doesn’t challenge you, it won’t change you.",
  "Be so good they can’t ignore you.",
  "Don’t let yesterday take up too much of today.",
  "You don’t need to see the whole staircase, just take the first step.",
  "Do what is right, not what is easy.",
  "Your dreams don’t work unless you do.",
  "Push through the pain. Persevere through the struggle.",
  "Stop wishing, start doing.",
  "Be fearless in the pursuit of what sets your soul on fire.",
  "Your attitude determines your direction.",
  "Make each day your masterpiece.",
  "If you can dream it, you can do it.",
  "Life is tough, but so are you.",
  "Don’t wait for opportunity. Create it.",
  "You are capable of amazing things.",
  "Start each day with a positive thought.",
  "The secret of success is constancy of purpose.",
  "Believe in the power of yet.",
  "Do the hard jobs first. The easy jobs will take care of themselves.",
  "Success is no accident. It is hard work, perseverance, learning, studying, sacrifice, and love of what you are doing.",
  "You don’t have to be perfect to be amazing.",
  "The best way out is always through.",
  "You can if you think you can.",
  "Success is not for the lazy.",
  "If you want it, work for it.",
  "Courage doesn’t always roar. Sometimes courage is the quiet voice at the end of the day saying, ‘I will try again tomorrow.’",
  "Don’t let small minds convince you that your dreams are too big.",
  "Success is getting what you want. Happiness is wanting what you get.",
  "Strive for progress, not perfection.",
  "Turn your wounds into wisdom.",
  "You are braver than you believe, stronger than you seem, and smarter than you think.",
  "A year from now you may wish you had started today.",
  "Great things never come from comfort zones.",
  "Dreams don’t work unless you do.",
  "Start today. Not tomorrow.",
  "Be a voice, not an echo.",
  "Your life does not get better by chance, it gets better by change.",
  "Focus on being productive instead of busy.",
  "Don’t stop until you’re proud."
],
love: [
  "Love is composed of a single soul inhabiting two bodies.",
  "Where there is love, there is life.",
  "You are my today and all of my tomorrows.",
  "Love is not what you say, it's what you do.",
  "I love you not because of who you are, but because of who I am when I am with you.",
  "Love is when the other person's happiness is more important than your own.",
  "You don’t love someone for their looks or their clothes or for their fancy car, but because they sing a song only you can hear.",
  "To love and be loved is to feel the sun from both sides.",
  "Love is the only force capable of transforming an enemy into a friend.",
  "You are every reason, every hope, and every dream I’ve ever had.",
  "The best thing to hold onto in life is each other.",
  "Love is a friendship set to music.",
  "I have found the one whom my soul loves.",
  "You are my heart, my life, my one and only thought.",
  "Love is not about how many days, months, or years you’ve been together. Love is about how much you love each other every single day.",
  "In all the world, there is no heart for me like yours.",
  "You are my sun, my moon, and all my stars.",
  "Love is like the wind, you can’t see it but you can feel it.",
  "I love you more than there are stars in the sky and fish in the sea.",
  "Being deeply loved by someone gives you strength, while loving someone deeply gives you courage.",
  "Love recognizes no barriers.",
  "Every love story is beautiful, but ours is my favorite.",
  "I saw that you were perfect, and so I loved you.",
  "You are the finest, loveliest, tenderest, and most beautiful person I have ever known—and even that is an understatement.",
  "Love is not something you find. Love is something that finds you.",
  "You are my paradise and I would happily get stranded on you for a lifetime.",
  "Love doesn’t make the world go round. Love is what makes the ride worthwhile.",
  "I love you without knowing how, or when, or from where.",
  "My heart is, and always will be, yours.",
  "To the world you may be one person, but to one person you are the world.",
  "I fell in love with you because of all the little things you do.",
  "Love is the only reality and it is not a mere sentiment. It is the ultimate truth.",
  "Every moment I spend with you is like a beautiful dream come true.",
  "You make my heart smile.",
  "I choose you. And I’ll choose you over and over and over. Without pause, without a doubt, in a heartbeat. I’ll keep choosing you.",
  "Love is not about possession. Love is about appreciation.",
  "You are my favorite notification.",
  "Love is like a friendship caught on fire.",
  "I still fall for you every day.",
  "Where there is love there is life.",
  "Love is a canvas furnished by nature and embroidered by imagination.",
  "If I know what love is, it is because of you.",
  "You are my today and all of my tomorrows.",
  "Love is not finding someone to live with. It’s finding someone you can’t live without.",
  "You have bewitched me, body and soul, and I love… I love… I love you.",
  "Being in love with you makes every morning worth getting up for.",
  "Love is the only gold.",
  "You are my heart’s epic adventure.",
  "Love is the flower you’ve got to let grow.",
  "You are the love that came without warning; you had my heart before I could say no.",
  "I love you more than yesterday, but not as much as tomorrow.",
  "You are my favorite reason to lose sleep.",
  "Love is composed of a single soul inhabiting two bodies.",
  "I wish I could turn back the clock. I’d find you sooner and love you longer.",
  "You are my heart, my soul, my treasure, my today, my tomorrow, my forever.",
  "Love is friendship that has caught fire.",
  "When I follow my heart, it leads me to you.",
  "I want all of you, forever, you and me, every day.",
  "You’re the first and last thing on my mind each and every day.",
  "Love is the bridge between two hearts.",
  "I love you not only for what you are, but for what I am when I am with you.",
  "I have waited for you my entire life.",
  "My love for you is a journey, starting at forever and ending at never.",
  "You are my heart’s home.",
  "You are my greatest adventure.",
  "Love doesn’t make sense; it just is.",
  "I still get butterflies just thinking about you.",
  "You are the best part of me.",
  "To be brave is to love someone unconditionally, without expecting anything in return.",
  "You are my happily ever after.",
  "Love is the closest thing we have to magic.",
  "You are my heart, my life, my one and only thought.",
  "Love is like the wind, it cannot be seen but can be felt.",
  "I’ve fallen in love many times… always with you.",
  "You are the poem I never knew how to write and this life is the story I always wanted to tell.",
  "Love is a promise delivered already.",
  "You are my love story.",
  "With you, I’ve found the meaning of forever.",
  "Every day I love you more than yesterday.",
  "You are the piece that completes my heart.",
  "In your smile, I see something more beautiful than the stars.",
  "I still get lost in your eyes.",
  "You are my dream come true.",
  "Love is a game that two can play and both win.",
  "You are the reason I look forward to tomorrow.",
  "I want to grow old with you and still be in love every day.",
  "Being with you feels like home.",
  "My heart is perfect because you are inside.",
  "I love you endlessly.",
  "You are the melody to my heart.",
  "You make my world a better place.",
  "I am yours, don’t give myself back to me.",
  "You are my favorite everything.",
  "You are my heart’s desire.",
  "In you, I’ve found the love of my life and my closest, truest friend.",
  "I would find you in any lifetime.",
  "Love is the answer to everything in life.",
  "You are my forever and always.",
  "You are my sweetest hello and hardest goodbye.",
  "To love is to receive a glimpse of heaven.",
  "You are my reason, my hope, my happiness."
]
};
const moodSelect = document.getElementById("mood");
const quoteText = document.getElementById("quote-text");
const newQuoteBtn = document.getElementById("generateBtn");
if (newQuoteBtn) {
  newQuoteBtn.addEventListener("click", generateQuote);
}
function getRandomQuote(arr) {
  return arr[Math.floor(Math.random() * arr.length)];
}
function generateQuote() {
  const mood = moodSelect.value;
  let finalQuote = "";
  if (mood === "random") {
    const categories = Object.values(quotes);
    finalQuote = getRandomQuote(getRandomQuote(categories));
  } else {
    finalQuote = getRandomQuote(quotes[mood]);
  }
  quoteText.style.opacity = 0;
  setTimeout(() => {
    quoteText.textContent = finalQuote;
    quoteText.style.opacity = 1;
  }, 200);
}
newQuoteBtn.addEventListener("click", generateQuote);